# ==========================================================
# email_sender.py — Email Notification Module
# ==========================================================
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


def get_email_config():
    """Load email configuration from environment variables."""
    return {
        "smtp_host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
        "smtp_port": int(os.getenv("SMTP_PORT", 587)),
        "smtp_user": os.getenv("SMTP_USER", ""),
        "smtp_password": os.getenv("SMTP_PASSWORD", ""),
        "recipients": os.getenv("EMAIL_RECIPIENTS", "").split(","),
    }


def create_email_body(summary: dict) -> str:
    """Create HTML email body from moderation summary."""
    
    timestamp = summary.get("sync_timestamp", "N/A")
    service_count = summary.get("service_records", 0)
    provider_count = summary.get("provider_records", 0)
    total_processed = summary.get("total_records_processed", 0)
    flagged_count = summary.get("flagged_entities", 0)
    db_rows = summary.get("db_rows_written", 0)
    batches = summary.get("batches", 0)

    # Determine status color
    if flagged_count > 0:
        status_color = "#e74c3c"  # Red
        status_text = "⚠️ Review Required"
    else:
        status_color = "#27ae60"  # Green
        status_text = "✅ All Clear"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                       color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
            .content {{ background: #f9f9f9; padding: 20px; border: 1px solid #ddd; }}
            .stat-box {{ display: inline-block; background: white; padding: 15px 20px; 
                         margin: 5px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            .stat-value {{ font-size: 24px; font-weight: bold; color: #667eea; }}
            .stat-label {{ font-size: 12px; color: #888; text-transform: uppercase; }}
            .status {{ background: {status_color}; color: white; padding: 10px 20px; 
                       border-radius: 4px; display: inline-block; margin: 15px 0; }}
            .footer {{ background: #333; color: #aaa; padding: 15px; font-size: 12px; 
                       border-radius: 0 0 8px 8px; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1 style="margin:0;">📊 Content Moderation Report</h1>
                <p style="margin:5px 0 0 0; opacity:0.9;">Automated Pipeline Summary</p>
            </div>
            <div class="content">
                <p><strong>Sync Timestamp:</strong> {timestamp}</p>
                
                <div class="status">{status_text}</div>
                
                <h3>📈 Processing Summary</h3>
                <div>
                    <div class="stat-box">
                        <div class="stat-value">{service_count}</div>
                        <div class="stat-label">Services</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{provider_count}</div>
                        <div class="stat-label">Providers</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{total_processed}</div>
                        <div class="stat-label">Total Processed</div>
                    </div>
                </div>
                
                <h3>🔍 Moderation Results</h3>
                <div>
                    <div class="stat-box">
                        <div class="stat-value" style="color: {status_color};">{flagged_count}</div>
                        <div class="stat-label">Flagged Entities</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{db_rows}</div>
                        <div class="stat-label">DB Rows Written</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{batches}</div>
                        <div class="stat-label">Batches Processed</div>
                    </div>
                </div>
                
                {"<p style='margin-top:20px;'><strong>📎 Attachment:</strong> Review report CSV attached.</p>" if flagged_count > 0 else ""}
            </div>
            <div class="footer">
                Generated by Content Moderation API • {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
            </div>
        </div>
    </body>
    </html>
    """
    return html


def send_moderation_report_email(
    summary: dict,
    csv_path: str = None,
    recipients: list = None,
    subject: str = None
) -> dict:
    """
    Send moderation report email with optional CSV attachment.
    
    Args:
        summary: Dict containing moderation pipeline results
        csv_path: Optional path to CSV file to attach
        recipients: List of email addresses (uses env config if None)
        subject: Email subject (auto-generated if None)
    
    Returns:
        Dict with status and message
    """
    
    config = get_email_config()
    
    # Validate config
    if not config["smtp_user"] or not config["smtp_password"]:
        return {
            "success": False,
            "message": "SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD."
        }
    
    # Use provided recipients or fall back to config
    if recipients is None:
        recipients = [r.strip() for r in config["recipients"] if r.strip()]
    
    if not recipients:
        return {
            "success": False,
            "message": "No email recipients configured. Set EMAIL_RECIPIENTS."
        }
    
    # Generate subject if not provided
    if subject is None:
        flagged = summary.get("flagged_entities", 0)
        if flagged > 0:
            subject = f"⚠️ Content Moderation Alert: {flagged} entities require review"
        else:
            subject = "✅ Content Moderation Report: All Clear"
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg["From"] = config["smtp_user"]
        msg["To"] = ", ".join(recipients)
        msg["Subject"] = subject
        
        # Attach HTML body
        html_body = create_email_body(summary)
        msg.attach(MIMEText(html_body, "html"))
        
        # Attach CSV if provided and file exists
        if csv_path and os.path.exists(csv_path):
            with open(csv_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                
                filename = os.path.basename(csv_path)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={filename}"
                )
                msg.attach(part)
        
        # Send email
        with smtplib.SMTP(config["smtp_host"], config["smtp_port"]) as server:
            server.starttls()
            server.login(config["smtp_user"], config["smtp_password"])
            server.sendmail(config["smtp_user"], recipients, msg.as_string())
        
        return {
            "success": True,
            "message": f"Email sent successfully to {len(recipients)} recipient(s)",
            "recipients": recipients
        }
    
    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "message": "SMTP authentication failed. Check your credentials."
        }
    except smtplib.SMTPException as e:
        return {
            "success": False,
            "message": f"SMTP error: {str(e)}"
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Failed to send email: {str(e)}"
        }
